Added solutions to all challenge probelms from codechef
amanBhawsar/Coding-Tree pull request #5
Opened 2020-10-18 20:31 UTC by NavyaIyanampudi

Please find all the codes below!
Hope it helps

2020-10-19 18:00 UTC, amanBhawsar requested changes
Remove the code which are already there. 
I have added some comments kindly resolve them and raise PR.
Good Luck

2020-10-19 18:00 UTC, amanBhawsar commented on CodechefChallengeSolutions/APRIL20B/SQRDSUB.cpp
> +#include <iostream>
already there

2020-10-19 18:00 UTC, amanBhawsar commented on CodechefChallengeSolutions/APRIL20B/STRNO.cpp
> +#include <bits/stdc++.h>
already there

2020-10-19 18:00 UTC, amanBhawsar commented on CodechefChallengeSolutions/APRIL20B/UNITGCD.cpp
> +{
remove unwanted code

2020-10-19 18:00 UTC, amanBhawsar commented on CodechefChallengeSolutions/DEC19B/WATSCORE.cpp
> +long long maxi(int);
no need of line no 20

2020-10-19 18:00 UTC, amanBhawsar commented on CodechefChallengeSolutions/DEC19B/WATSCORE.cpp
> +void init();
no need of line no 11

2020-10-19 18:00 UTC, amanBhawsar commented on CodechefChallengeSolutions/JULY20B/CHEFSTR1.cpp
> +	    cout<<"\n";
you could have written it in single cout statement

2020-10-19 18:00 UTC, amanBhawsar commented on CodechefChallengeSolutions/LTIME74B/RPD.c
> +    int a[1000],sum=0,q=0,k,n,i,j,max=0,num=0,digit=0,m=0,temp=0;
remove unused variables like temp

2020-10-19 18:00 UTC, amanBhawsar commented on CodechefChallengeSolutions/LTIME81B/POPGATES.cpp
> +    ll  w, a,b,c,d,n,m,k,t;
remove unused var a,b,c etc

2020-10-19 18:00 UTC, amanBhawsar commented on CodechefChallengeSolutions/MARCH20B/ENGXOR.cpp
> +	cin.tie(NULL);
if you are using these 2 lines then no need to use scanf/printf you can directly use cin/cout with same i/o speed

2020-10-19 18:00 UTC, amanBhawsar commented on CodechefChallengeSolutions/UWCOI20/UWCOI20A.cpp
> +	    cin>>a[i];
you could have done it in O(1) space if compared the element while taking input.

2020-10-19 18:08 UTC, NavyaIyanampudi commented on CodechefChallengeSolutions/APRIL20B/SQRDSUB.cpp
> +#include <iostream>
Deleted!

2020-10-19 18:12 UTC, NavyaIyanampudi commented on CodechefChallengeSolutions/DEC19B/WATSCORE.cpp
> +long long maxi(int);
Done

2020-10-19 18:17 UTC, NavyaIyanampudi commented on CodechefChallengeSolutions/MARCH20B/ENGXOR.cpp
> +	cin.tie(NULL);
Sure

2020-10-19 18:19 UTC, NavyaIyanampudi commented on CodechefChallengeSolutions/UWCOI20/UWCOI20A.cpp
> +	    cin>>a[i];
Will *max_element take any space I mean other than constant space?

2020-10-19 18:23 UTC, NavyaIyanampudi reviewed
I made all the changes as you said.
Thank you for your time really helped me

2020-10-19 18:25 UTC, NavyaIyanampudi commented
@amanBhawsar Please check and confirm

2020-10-20 16:48 UTC, amanBhawsar commented on CodechefChallengeSolutions/UWCOI20/UWCOI20A.cpp
> +	    cin>>a[i];
Nope I was referring to the input array

2020-10-20 16:51 UTC, amanBhawsar approved these changes

2020-10-20 16:51 UTC, merged